version: '3.5'

services:
  www:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.dev:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend

  backend:
    container_name: codeigniter3-vuejs
    image: codeigniter3-vuejs
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/application/vendor
    ports:
      - 8081:80

  frontend:
    container_name: codeigniter3-vuejs_frontend
    image: codeigniter3-vuejs_frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.vue
    volumes:
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./public:/app/public
    ports:
      - 8082:8080